name: Deploy Production

on:
  push:
    branches: [ main ]

    jobs:

      test:
        name: Unit tests
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v3

          - name: Set up JDK 17
            uses: actions/setup-java@v3
            with:
              distribution: 'temurin'
              java-version: 17
              cache: 'gradle'

          - name: Grand execute permissions to gradlew
            run: chmod +x gradlew

          - name: Run unit tests
            run: ./gradlew testDebug

      distribute:
        name: Distribute App
        needs: test
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v3

          - name: Set Up JDK 17
            uses: actions/setup-java@v3
            with:
              distribution: 'temurin'
              java-version: 17
              cache: 'gradle'

          - name: Version Bump
            uses: chkfung/android-version-actions@v1.2.1
            with:
              gradlePath: app/build.gradle
              versionCode: ${{ github.run_number }}

          - name: Assemble Release Bundle
            run: ./gradlew bundleRelease

          - name: Sign Release
            uses: r0adkll/sign-android-release@v1
            with:
              releaseDirectory: app/build/outputs/bundle/release
              signingKeyBase64: ${{ secrets.KEYSTORE }}
              keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
              alias: ${{ secrets.APP_NAME_KEY }}
              keyPassword: ${{ secrets.APP_NAME_KEY_PASSWORD }}

          - name: Setup Authorization With Google Play Store
            run: echo '${{ secrets.GOOGLE_PLAY_API_AUTH }}' > service_account.json

          - name: Deploy to Internal Channel
            uses: r0adkll/upload-google-play@v1.0.19
            with:
              serviceAccountJson: service_account.json
              packageName: com.example.mytestapplication
              releaseFiles: app/build/outputs/bundle/release/app-release.aab
              track: internal
              status: 'completed'
              whatsNewDirectory: whatsNewDirectory/